## Put comments here that give an overall description of what your
## functions do

## This function is responsables to generate a cache_matrix object

makeCacheMatrix <- function(x = matrix()) {
    # the variable that will cache the inversion values
    cache_inversion <- NULL

    # this function resolves the inversion and cache it into the variable
    solve_inversion <- function() cache_inversion <<- solve(matrix)

    # this function return the value from the cache variable
    get_inversion <- function() cache_inversion

    # this generates an object with the values of the closure.
    # I add only 2 methods because those methods where the ones
    # needed to fetch the matrix inversion.
    list(solve_inversion = solve_inversion, get_inversion = get_inversion)
}


## This function is responsable to resolve a cache matrix object
## generated by the function makeCacheMatrix, if the object already
## has cached results, return those otherwise it generates new ones

cacheSolve <- function(x, ...) {
    # This fetch the information from the cache object
    inversion <- cache_matrix$get_inversion()

    # return the values from the cache object
    fetch_cache_inversion <- function() {
        message("getting inversion from cached data")
        inversion
    }

   # solve the inversion and return new values
   fetch_inversion <- function() {
       message("generating a new inversion")
       cache_matrix$solve_inversion()
       cache_matrix$get_inversion()
   }

   if(!is.null(inversion)) return(fetch_cache_inversion())
   fetch_inversion()
}
